/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Mail (SQLite)
 #	author : miyako
 #	4/25/18
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

// --- Mail
void Mail_Get_message_properties(sLONG_PTR *pResult, PackagePtr pParams);
